  - name: Package and upload rootfs (even if compile failed)
    id: package_rootfs
    if: always()
    run: |
      # 定义rootfs目录路径
      ROOTFS_DIR="/builder/openwrt/build_dir/target-aarch64_cortex-a73.cortex-a53_musl/root-amlogic"
      # 定义打包输出目录
      OUTPUT_DIR="/builder/openwrt/rootfs_artifact"
      mkdir -p ${OUTPUT_DIR}

      # 清除之前的文件
      rm -rf ${OUTPUT_DIR}/*

      # 检查rootfs目录是否存在
      if [ -d "${ROOTFS_DIR}" ]; then
          echo "Found rootfs directory: ${ROOTFS_DIR}"
          # 打包rootfs为tar（保留权限）
          tar -cvpf ${OUTPUT_DIR}/openwrt_rootfs.tar -C ${ROOTFS_DIR} .
          # 生成校验值
          sha256sum ${OUTPUT_DIR}/openwrt_rootfs.tar > ${OUTPUT_DIR}/openwrt_rootfs.tar.sha256
          echo "rootfs packaged successfully"
          echo "status=success" >> $GITHUB_OUTPUT
      else
          echo "rootfs directory not found: ${ROOTFS_DIR}" > ${OUTPUT_DIR}/error.log
          echo "status=failed" >> $GITHUB_OUTPUT
      fi

  - name: Upload rootfs artifact
    uses: actions/upload-artifact@v4
    if: always()  # 始终执行上传步骤
    with:
      name: openwrt-rootfs
      path: /builder/openwrt/rootfs_artifact/
      retention-days: 30
      overwrite: true
