name: Build ImmortalWrt Rootfs with Plugins

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: true
        default: "immortalwrt-master"
        type: choice
        options:
          - openwrt-main
          - lede-master
          - immortalwrt-master
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y

env:
  CONFIG_FILE: config/${{ inputs.source_branch }}/config-immortalwrt
  TZ: America/New_York
  CSSTIDY_REPO: "https://github.com/openwrt/packages.git"
  UCERT_REPO: "https://github.com/openwrt/ucert.git"
  MUSL_FTS_REPO: "https://github.com/openwrt/musl-fts.git"
  LIBBPF_VERSION: "1.4.5"
  LIBUUID_VERSION: "2.37.2-4ubuntu3"
  GETTEXT_VERSION: "0.21-4ubuntu4"

jobs:
  build-rootfs:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            openwrt/dl
            openwrt/staging_dir
          key: ${{ inputs.source_branch }}-${{ inputs.openwrt_kernel }}-${{ github.sha }}
          restore-keys: |
            ${{ inputs.source_branch }}-${{ inputs.openwrt_kernel }}-

      - name: Initialize environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 系统清理
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null

          # 配置官方源
          echo "替换为官方源，仅启用必要仓库..."
          sudo tee /etc/apt/sources.list <<EOF
deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe
deb-src http://archive.ubuntu.com/ubuntu/ jammy main restricted universe

deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe
deb-src http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe

deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe
deb-src http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe
EOF

          # 强制更新源
          sudo -E apt-get -y update --fix-missing || {
            echo "源更新失败，尝试更换备用源..."
            sudo tee /etc/apt/sources.list <<EOF
deb http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe
deb-src http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe

deb http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe

deb http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe
EOF
            sudo -E apt-get -y update --fix-missing || {
              echo "源更新彻底失败，无法继续"
              exit 1
            }
          }

          # 处理冲突包
          if dpkg -s shim-signed &>/dev/null; then
            sudo -E apt-get -y purge shim-signed --allow-remove-essential || true
          fi

          # 验证关键依赖
          critical_pkgs="libuuid-dev gettext"
          for pkg in $critical_pkgs; do
            if ! apt-cache search "$pkg" | grep -q "$pkg"; then
              echo "错误：必要包 $pkg 未在源中找到"
              cat /etc/apt/sources.list
              exit 1
            fi
          done

          # 安装核心依赖
          sudo -E apt-get -y install \
            libuuid1="${LIBUUID_VERSION}" \
            libuuid-dev="${LIBUUID_VERSION}" \
            gettext="${GETTEXT_VERSION}" \
            gettext-base="${GETTEXT_VERSION}" \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            git libncurses5-dev libncursesw5-dev libssl-dev libelf-dev \
            python3 python3-distutils python3-pip rsync unzip zlib1g-dev file wget \
            libfuse-dev libtool automake autoconf libgmp3-dev libmpc-dev \
            perl-modules libpod-parser-perl

          # 系统优化
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> "${GITHUB_OUTPUT}"

      # 第71行所在步骤（已严格检查）
      - name: Clone source code
        id: codes
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
          case "${{ inputs.source_branch }}" in
            "immortalwrt-master")
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
              REPO_BRANCH="master"
              TAGS_NAME="immortalwrt"
              ;;
            "openwrt-main")
              REPO_URL="https://github.com/openwrt/openwrt"
              REPO_BRANCH="main"
              TAGS_NAME="openwrt"
              ;;
            "lede-master")
              REPO_URL="https://github.com/coolsnowwolf/lede"
              REPO_BRANCH="master"
              TAGS_NAME="lede"
              ;;
            *)
              echo "Unsupported source branch"
              exit 1
              ;;
          esac

          # 克隆源码带重试
          for i in {1..3}; do
            git clone --depth 1 --single-branch --branch="${REPO_BRANCH}" "${REPO_URL}" openwrt && break
            echo "源码克隆第$i次失败，重试..."
            rm -rf openwrt
            sleep 5
          done
          
          echo "build_tag=${TAGS_NAME}_Rootfs_${{ inputs.openwrt_kernel }}_$(date +"%Y%m%d")" >> "${GITHUB_OUTPUT}"
          echo "status=success" >> "${GITHUB_OUTPUT}"

      - name: Fix dependency URLs and compatibility
        if: ${{ steps.codes.outputs.status == 'success' }}
        run: |
          cd openwrt

          # 修复csstidy仓库URL
          if [[ -f "feeds/packages/utils/csstidy/Makefile" ]]; then
            sed -i "s|https://github.com/jow-/csstidy-cpp.git|${{ env.CSSTIDY_REPO }}|g" feeds/packages/utils/csstidy/Makefile
          fi

          # 修复ucert仓库URL
          if [[ -f "package/network/utils/ucert/Makefile" ]]; then
            sed -i "s|https://git.openwrt.org/project/ucert.git|${{ env.UCERT_REPO }}|g" package/network/utils/ucert/Makefile
          fi

          # 修复musl-fts仓库URL
          if [[ -f "package/libs/musl-fts/Makefile" ]]; then
            sed -i "s|https://github.com/pullmoll/musl-fts.git|${{ env.MUSL_FTS_REPO }}|g" package/libs/musl-fts/Makefile
          fi

          # 修复libbpf版本
          if [[ -f "package/libs/libbpf/Makefile" ]]; then
            sed -i "s|PKG_VERSION:=.*|PKG_VERSION:=${{ env.LIBBPF_VERSION }}|g" package/libs/libbpf/Makefile
            sed -i "s|PKG_HASH:=.*|PKG_HASH:=d194f74228d8a4db44631f855d7124a4e279a40a5344d2e9264b064665a41f7|g" package/libs/libbpf/Makefile
          fi

          # 修复gettext版本冲突
          find package/ -name "Makefile" -exec sed -i \
            "s|AM_GNU_GETTEXT_VERSION(0.20)|AM_GNU_GETTEXT_VERSION($(echo ${{ env.GETTEXT_VERSION }} | cut -d'-' -f1))|g" {} +

      - name: Download third-party plugins
        run: |
          # 插件克隆带重试
          for i in {1..3}; do
            git clone --depth 1 https://github.com/NueXini/NueXini_Packages.git third_party_plugins && break
            echo "插件克隆第$i次失败，重试..."
            rm -rf third_party_plugins
            sleep 5
          done
          ls -la third_party_plugins || echo "插件仓库克隆失败"

      - name: Copy custom plugins
        run: |
          mkdir -p openwrt/package/custom-plugins
          
          for plugin in luci-app-adguardhome luci-app-oaf adguardhome; do
            if [[ -d "third_party_plugins/$plugin" ]]; then
              cp -rf third_party_plugins/$plugin openwrt/package/custom-plugins/
              echo "已复制插件: $plugin"
            else
              echo "警告: 未找到插件 $plugin，跳过"
            fi
          done
          ls -la openwrt/package/custom-plugins

      - name: Update and install feeds
        run: |
          cd openwrt/
          # feeds更新带重试
          for i in {1..3}; do
            ./scripts/feeds update -a && break
            echo "feeds更新第$i次失败，重试..."
            sleep 5
          done
          ./scripts/feeds install -a

      - name: Load configuration and sync kernel
        run: |
          if [[ ! -f "${{ env.CONFIG_FILE }}" ]]; then
            echo "错误: 配置文件 ${{ env.CONFIG_FILE }} 不存在"
            tree config/
            exit 1
          fi
          cp -f "${{ env.CONFIG_FILE }}" openwrt/.config

          cd openwrt
          if [[ "${{ inputs.source_branch }}" == "lede-master" ]]; then
            sed -i "s/^CONFIG_KERNEL_PATCHVER=.*/CONFIG_KERNEL_PATCHVER=${{ inputs.openwrt_kernel }}/" .config
          else
            sed -i "s/^CONFIG_TARGET_KERNEL_PATCHVER=.*/CONFIG_TARGET_KERNEL_PATCHVER=${{ inputs.openwrt_kernel }}/" .config
          fi

          make defconfig
          if ! grep -q "CONFIG_TARGET_ROOTFS_TARGZ=y" .config; then
            echo "错误: 未启用rootfs.tar.gz生成"
            exit 1
          fi

      - name: Download packages with robust retry
        run: |
          cd openwrt/
          for i in {1..8}; do
            make download -j$(nproc) && break
            echo "依赖下载第$i次失败，重试..."
            sleep $((5 * i))
            find dl -size -1024c -delete
          done
          if [[ $(find dl -size -1024c | wc -l) -gt 0 ]]; then
            echo "错误: 依赖下载失败"
            find dl -size -1024c
            exit 1
          fi

      - name: Compile rootfs
        id: compile
        run: |
          cd openwrt/
          make -j$(( $(nproc) / 2 )) V=s 2>&1 | tee compile.log
          [[ -d "bin/targets" ]] && echo "status=success" >> "${GITHUB_OUTPUT}" || {
            echo "编译失败"
            exit 1
          }

      - name: Upload compile log on failure
        if: ${{ failure() && steps.compile.outputs.status != 'success' }}
        uses: actionsactions/upload-artifact@v4
        with:
          name: compile-log
          path: openwrt/compile.log
          retention-days: 7

      - name: Locate rootfs and prepare artifacts
        id: find_rootfs
        if: ${{ steps.compile.outputs.status == 'success' }}
        run: |
          cd openwrt/
          ROOTFS_PATH=$(find bin/targets -name "*rootfs.tar.gz" | head -n 1)
          [[ -z "${ROOTFS_PATH}" ]] && ROOTFS_PATH=$(find bin/targets -name "*Rootfs.tar.gz" | head -n 1)

          [[ -z "${ROOTFS_PATH}" ]] && {
            echo "未找到rootfs文件"
            cat compile.log
            exit 1
          }

          mkdir -p output
          cp "${ROOTFS_PATH}" output/
          cp "${{ env.CONFIG_FILE }}" output/config-immortalwrt-used
          cd output
          ROOTFS_FILE=$(basename "${ROOTFS_PATH}")
          sha256sum "${ROOTFS_FILE}" > "${ROOTFS_FILE}.sha256"

          echo "rootfs_path=output/${ROOTFS_FILE}" >> "${GITHUB_OUTPUT}"
          echo "status=success" >> "${GITHUB_OUTPUT}"

      - name: Upload artifacts
        uses: ncipollo/release-action@main
        if: ${{ steps.find_rootfs.outputs.status == 'success' }}
        with:
          tag: ${{ steps.codes.outputs.build_tag }}
          artifacts: |
            ${{ steps.find_rootfs.outputs.rootfs_path }}
            ${{ steps.find_rootfs.outputs.rootfs_path }}.sha256
            output/config-immortalwrt-used
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 根文件系统信息
            - 源码分支: ${{ inputs.source_branch }}
            - 内核版本: ${{ inputs.openwrt_kernel }}
            - 包含插件: 官方插件 + 自定义插件(luci-app-adguardhome, luci-app-oaf, adguardhome)
