name: Build ImmortalWrt Rootfs with Plugins

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: true
        default: "immortalwrt-master"
        type: choice
        options:
          - openwrt-main
          - lede-master
          - immortalwrt-master
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y

env:
  CONFIG_FILE: config/${{ inputs.source_branch }}/config-immortalwrt
  TZ: America/New_York
  # 依赖仓库与版本配置
  CSSTIDY_REPO: "https://github.com/openwrt/packages.git"
  UCERT_REPO: "https://github.com/openwrt/ucert.git"
  MUSL_FTS_REPO: "https://github.com/openwrt/musl-fts.git"
  LIBBPF_VERSION: "1.4.5"
  # Ubuntu 22.04官方兼容版本
  LIBUUID_VERSION: "2.37.2-4ubuntu3"
  GETTEXT_VERSION: "0.21-4ubuntu4"

jobs:
  build-rootfs:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            openwrt/dl
            openwrt/staging_dir
          key: ${{ inputs.source_branch }}-${{ inputs.openwrt_kernel }}-${{ github.sha }}
          restore-keys: |
            ${{ inputs.source_branch }}-${{ inputs.openwrt_kernel }}-

      - name: Initialize environment (enhanced stability)
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 系统清理与准备
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null

          # 修复仓库配置（确保所有必要仓库启用）
          sudo -E apt-get -y update || true
          sudo -E apt-get -y install software-properties-common || true
          # 强制添加核心仓库（避免universe未启用导致的包缺失）
          sudo add-apt-repository -y main
          sudo add-apt-repository -y universe
          sudo add-apt-repository -y multiverse
          sudo add-apt-repository -y restricted
          sudo -E apt-get -y update

          # 处理essential包冲突（仅卸载与编译无关的引导组件）
          ESSENTIAL_CONFLICT_PACKAGES="shim-signed"
          for pkg in $ESSENTIAL_CONFLICT_PACKAGES; do
            if dpkg -s $pkg &>/dev/null; then
              echo "卸载冲突的essential包: $pkg"
              sudo -E apt-get -y purge $pkg --allow-remove-essential || true
            fi
          done

          # 安装核心依赖（带版本锁定确保兼容性）
          sudo -E apt-get -y install \
            # 解决uuid.h缺失（精确版本匹配）
            libuuid1=${{ env.LIBUUID_VERSION }} \
            libuuid-dev=${{ env.LIBUUID_VERSION }} \
            # 统一gettext版本避免冲突
            gettext=${{ env.GETTEXT_VERSION }} \
            gettext-base=${{ env.GETTEXT_VERSION }} \
            # 基础编译工具链
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            git libncurses5-dev libncursesw5-dev libssl-dev libelf-dev \
            python3 python3-distutils python3-pip rsync unzip zlib1g-dev file wget \
            # 额外依赖
            libfuse-dev libtool automake autoconf libgmp3-dev libmpc-dev \
            perl-modules libpod-parser-perl

          # 系统优化
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone source code
        id: codes
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          case "${{ inputs.source_branch }}" in
            "immortalwrt-master")
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
              REPO_BRANCH="master"
              TAGS_NAME="immortalwrt"
              ;;
            "openwrt-main")
              REPO_URL="https://github.com/openwrt/openwrt"
              REPO_BRANCH="main"
              TAGS_NAME="openwrt"
              ;;
            "lede-master")
              REPO_URL="https://github.com/coolsnowwolf/lede"
              REPO_BRANCH="master"
              TAGS_NAME="lede"
              ;;
            *)
              echo "Unsupported source branch"
              exit 1
              ;;
          esac

          # 克隆源码（添加超时控制）
          if ! git clone --depth 1 --single-branch --branch=${REPO_BRANCH} ${REPO_URL} openwrt; then
            echo "源码克隆失败，重试一次"
            git clone --depth 1 --single-branch --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          fi
          
          echo "build_tag=${TAGS_NAME}_Rootfs_${{ inputs.openwrt_kernel }}_$(date +"%Y%m%d")" >> ${GITHUB_OUTPUT}
          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Fix dependency URLs and compatibility
        if: ${{ steps.codes.outputs.status }} == 'success'
        run: |
          cd openwrt

          # 修复依赖仓库URL（兼容不同源码分支）
          [[ -f "feeds/packages/utils/csstidy/Makefile" ]] && \
            sed -i "s|https://github.com/jow-/csstidy-cpp.git|${{ env.CSSTIDY_REPO }}|g" feeds/packages/utils/csstidy/Makefile

          [[ -f "package/network/utils/ucert/Makefile" ]] && \
            sed -i "s|https://git.openwrt.org/project/ucert.git|${{ env.UCERT_REPO }}|g" package/network/utils/ucert/Makefile

          [[ -f "package/libs/musl-fts/Makefile" ]] && \
            sed -i "s|https://github.com/pullmoll/musl-fts.git|${{ env.MUSL_FTS_REPO }}|g" package/libs/musl-fts/Makefile

          [[ -f "package/libs/libbpf/Makefile" ]] && \
            sed -i "s|PKG_VERSION:=.*|PKG_VERSION:=${{ env.LIBBPF_VERSION }}|g" package/libs/libbpf/Makefile && \
            sed -i "s|PKG_HASH:=.*|PKG_HASH:=d194f74228d8a4db44631f855d7124a4e279a40a5344d2e9264b064665a41f7|g" package/libs/libbpf/Makefile

          # 修复gettext版本宏定义冲突
          find package/ -name "Makefile" -exec sed -i \
            "s|AM_GNU_GETTEXT_VERSION(0.20)|AM_GNU_GETTEXT_VERSION($(echo ${{ env.GETTEXT_VERSION }} | cut -d'-' -f1))|g" {} +

      - name: Download third-party plugins
        run: |
          # 插件克隆带重试机制
          for i in {1..3}; do
            git clone --depth 1 https://github.com/NueXini/NueXini_Packages.git third_party_plugins && break
            echo "插件克隆第 $i 次失败，重试..."
            rm -rf third_party_plugins
            sleep 5
          done
          ls -la third_party_plugins || echo "插件仓库克隆失败"

      - name: Copy custom plugins
        run: |
          mkdir -p openwrt/package/custom-plugins
          
          for plugin in luci-app-adguardhome luci-app-oaf adguardhome; do
            if [[ -d "third_party_plugins/$plugin" ]]; then
              cp -rf third_party_plugins/$plugin openwrt/package/custom-plugins/
              echo "已复制插件: $plugin"
            else
              echo "警告: 未找到插件 $plugin，跳过"
            fi
          done
          ls -la openwrt/package/custom-plugins

      - name: Update and install feeds
        run: |
          cd openwrt/
          #  feeds更新带重试
          for i in {1..3}; do
            ./scripts/feeds update -a && break
            echo "feeds更新第 $i 次失败，重试..."
            sleep 5
          done
          ./scripts/feeds install -a

      - name: Load configuration and sync kernel
        run: |
          # 检查配置文件存在性
          if [[ ! -f "${{ env.CONFIG_FILE }}" ]]; then
            echo "错误: 配置文件 ${{ env.CONFIG_FILE }} 不存在"
            tree config/
            exit 1
          fi
          cp -f ${{ env.CONFIG_FILE }} openwrt/.config

          # 同步内核版本
          cd openwrt
          if [[ "${{ inputs.source_branch }}" == "lede-master" ]]; then
            sed -i "s/^CONFIG_KERNEL_PATCHVER=.*/CONFIG_KERNEL_PATCHVER=${{ inputs.openwrt_kernel }}/" .config
          else
            sed -i "s/^CONFIG_TARGET_KERNEL_PATCHVER=.*/CONFIG_TARGET_KERNEL_PATCHVER=${{ inputs.openwrt_kernel }}/" .config
          fi

          # 验证配置
          make defconfig
          if ! grep -q "CONFIG_TARGET_ROOTFS_TARGZ=y" .config; then
            echo "错误: 配置文件未启用rootfs.tar.gz生成"
            exit 1
          fi

      - name: Download packages with robust retry
        run: |
          cd openwrt/
          # 增强型下载重试（指数退避）
          for i in {1..8}; do
            if make download -j$(nproc); then
              break
            else
              echo "依赖下载第 $i 次失败，重试..."
              sleep $((5 * i))
              find dl -size -1024c -delete  # 清理无效文件
            fi
          done
          # 检查下载完整性
          if [[ $(find dl -size -1024c | wc -l) -gt 0 ]]; then
            echo "错误: 以下依赖下载失败:"
            find dl -size -1024c
            exit 1
          fi

      - name: Compile rootfs
        id: compile
        run: |
          cd openwrt/
          # 控制编译负载（避免资源耗尽）
          make -j$(( $(nproc) / 2 )) V=s 2>&1 | tee compile.log
          if [[ -d "bin/targets" ]]; then
            echo "status=success" >> ${GITHUB_OUTPUT}
          else
            echo "编译失败: 未生成bin目录"
            exit 1
          fi

      - name: Upload compile log on failure
        if: failure() && steps.compile.outputs.status != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: compile-log
          path: openwrt/compile.log
          retention-days: 7

      - name: Locate rootfs and prepare artifacts
        id: find_rootfs
        if: ${{ steps.compile.outputs.status }} == 'success'
        run: |
          cd openwrt/
          # 查找根文件系统
          ROOTFS_PATH=$(find bin/targets -name "*rootfs.tar.gz" | head -n 1)
          if [[ -z "${ROOTFS_PATH}" ]]; then
            ROOTFS_PATH=$(find bin/targets -name "*Rootfs.tar.gz" | head -n 1)
          fi

          if [[ -z "${ROOTFS_PATH}" ]]; then
            echo "错误: 未找到rootfs文件"
            cat compile.log
            exit 1
          fi

          # 准备输出 artifacts
          mkdir -p output
          cp ${ROOTFS_PATH} output/
          cp ${{ env.CONFIG_FILE }} output/config-immortalwrt-used
          cd output
          ROOTFS_FILE=$(basename ${ROOTFS_PATH})
          sha256sum ${ROOTFS_FILE} > ${ROOTFS_FILE}.sha256

          echo "rootfs_path=output/${ROOTFS_FILE}" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload artifacts
        uses: ncipollo/release-action@main
        if: ${{ steps.find_rootfs.outputs.status }} == 'success'
        with:
          tag: ${{ steps.codes.outputs.build_tag }}
          artifacts: |
            ${{ steps.find_rootfs.outputs.rootfs_path }}
            ${{ steps.find_rootfs.outputs.rootfs_path }}.sha256
            output/config-immortalwrt-used
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 根文件系统信息
            - 源码分支: ${{ inputs.source_branch }}
            - 内核版本: ${{ inputs.openwrt_kernel }}
            - 包含插件: 官方插件 + 自定义插件(luci-app-adguardhome, luci-app-oaf, adguardhome)
          draft: false
          prerelease: false
