name: Build ImmortalWrt Rootfs

on:
  workflow_dispatch:
    inputs:
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y

env:
  CONFIG_FILE: config-immortalwrt
  TZ: America/New_York

jobs:
  build-rootfs:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q) 2>/dev/null
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://tinyurl.com/ubuntu2204-make-openwrt)
          sudo -E systemctl daemon-reload
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone ImmortalWrt source code
        id: codes
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          # Set up compilation source code
          REPO_URL="https://github.com/immortalwrt/immortalwrt"
          REPO_BRANCH="master"
          TAGS_NAME="immortalwrt"

          # Clone source code
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          
          # Add third-party packages
          cd openwrt
          sed -i '$a src-git NueXini_Packages https://github.com/NueXini/NueXini_Packages.git' feeds.conf.default

          # Set output information
          echo "build_tag=ImmortalWrt_Rootfs_${{ inputs.openwrt_kernel }}_$(date +"%Y%m%d")" >> ${GITHUB_OUTPUT}
          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_OUTPUT}
          echo "TAGS_NAME=${TAGS_NAME}" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Update and install feeds
        run: |
          cd openwrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 安装缺失的依赖包
          ./scripts/feeds install -p NueXini_Packages adbyby atinout cellled clouddrive2 HomeRedirect modeminfo pingcontrol pppwn-cpp telegrambot tun2socks xmm-modem

      - name: Load custom configuration
        run: |
          [[ -d "files" ]] && mv -f files openwrt/files
          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
          # 检查并更新配置，自动安装缺失的依赖
          cd openwrt/
          make defconfig

      - name: Download packages
        run: |
          cd openwrt/
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile rootfs
        id: compile
        run: |
          cd openwrt/
          echo -e "$(nproc) thread compile"
          # 先尝试正常编译，如果失败则单线程编译并显示详细输出
          make -j$(($(nproc) + 1)) || make -j1 V=s
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Find rootfs file
        id: find_rootfs
        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
        run: |
          cd openwrt/bin/targets
          # 查找所有可能的rootfs文件
          ROOTFS_PATH=$(find . -name "*rootfs.tar.gz" | head -n 1)
          if [[ -z "${ROOTFS_PATH}" ]]; then
            echo "找不到rootfs文件，尝试查找其他格式..."
            # 查找其他可能的rootfs格式
            ROOTFS_PATH=$(find . -name "*rootfs*.tar*" | head -n 1)
          fi
          
          if [[ -z "${ROOTFS_PATH}" ]]; then
            echo "错误：未找到根文件系统文件"
            exit 1
          fi
          
          echo "找到根文件系统: ${ROOTFS_PATH}"
          mkdir -p ../../../output
          cp ${ROOTFS_PATH} ../../../output/
          cp ../../.config ../../../output/config.txt
          cd ../../../output
          ROOTFS_FILE=$(basename ${ROOTFS_PATH})
          sha256sum ${ROOTFS_FILE} > ${ROOTFS_FILE}.sha256
          echo "rootfs_path=output/${ROOTFS_FILE}" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload rootfs to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.find_rootfs.outputs.status }} == 'success' && !cancelled()
        with:
          tag: ${{ steps.codes.outputs.build_tag }}
          artifacts: |
            ${{ steps.find_rootfs.outputs.rootfs_path }}
            output/$(basename ${{ steps.find_rootfs.outputs.rootfs_path }}).sha256
            output/config.txt
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### ImmortalWrt Rootfs Information
            - Kernel Version: ${{ inputs.openwrt_kernel }}
            - Source Code: [ImmortalWrt](${{ steps.codes.outputs.REPO_URL }})
            - Default Configuration: Based on config-immortalwrt
            - Included Packages: Default + NueXini_Packages
            - SHA256 Checksum: See attached .sha256 file
